{% set name = "checkmate" %}
{% set version = "0.9.487" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/adedayo/checkmate/archive/v{{ version }}.tar.gz
  sha256: 2331bd2d43f886c213635d8bb0e9ee93813bd5049eade4a5e1d8ac86e8c8b6dc

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - checkmate --help

about:
  home: https://github.com/adedayo/checkmate
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: CheckMate is a pluggable code security analysis tool that provides security analysis for your software and for configuration files associated with the software
  dev_url: https://github.com/adedayo/checkmate

extra:
  recipe-maintainers:
    - danielnachun
