{% set name = "checkmate" %}
{% set version = "0.9.48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/adedayo/checkmate/archive/v{{ version }}.tar.gz
  sha256: 871d3688bd00a6657c64db08788a1a53748248156b981c8035756f2c911cd181

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - checkmate --help

about:
  home: https://github.com/adedayo/checkmate
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: CheckMate is a pluggable code security analysis tool that provides security analysis for your software and for configuration files associated with the software
  dev_url: https://github.com/adedayo/checkmate

extra:
  recipe-maintainers:
    - danielnachun
