{% set name = "checkmate" %}
{% set version = "0.9.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/adedayo/checkmate/archive/v{{ version }}.tar.gz
  sha256: c3b58d4b55d4f3c10c8214c06a56579ab54ad85c399a66adc07ecb0c4a4482ab

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - checkmate --help

about:
  home: https://github.com/adedayo/checkmate
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: CheckMate is a pluggable code security analysis tool that provides security analysis for your software and for configuration files associated with the software
  dev_url: https://github.com/adedayo/checkmate

extra:
  recipe-maintainers:
    - danielnachun
